### ISSUE TITLE
Transform todo list to issues for contributors

### ISSUE THREAD

**Issue by nickspaargaren** [gafam/www.gafam.info#1]
Is the [TODO list](https://github.com/gafam/www.gafam.info/blob/main/TODO.rst#todo) up-to-date? It's a good idea to transform this list to Github issues so people like me can make pull requests and help complete this list.

**Comment by amotl** [comment]
Dear Nick,

thank you for writing in. The main aim of this project is to collect translations of those poster contents hosted at [1], to be rendered with the rendering engine hosted at [2].

There are various `todo.rst` and `backlog.rst` files spread across those projects, but they are merely notes we took while working on them. It is nothing we are actively pursuing in any way. We believe the project infrastructure is already strong enough to scale well on the axis of collecting more translations, so the projects are currently more or less in maintenance mode.

However, please let us know if you personally see any spots where improvements could be made and if you would like to work on some of them. We will always be happy to bring in contributions from the community.

With kind regards,
Andreas.

[1] https://github.com/gafam/gafam-poster-translations
[2] https://github.com/posterkit/posterkit-sandbox

**Comment by nickspaargaren** [comment]
Hi Andreas, thanks for your reply!

If the todo.rst and backlog.rst files were issues like this one you will be able to:
- Assign issues to a person.
- I will be able to Link a new pull request to that issue.
- We can mark them as done if a pull request is merged.

Do you want me to convert the todo.rst and backlog.rst lists to actual issues? That way I will be able to solve a few todo items and open pull requests that you can review and merge.

**Comment by amotl** [comment]
Dear Nick,

we cleaned up a bit, so that [1,2,3] is the outcome. Please do not blindly convert each and every item into actual issues, this will probably spam the issue tracker too much for such a small project.

On the other hand, picking important items or specific tasks you would like to work on into dedicated issues will be absolutely fine.

We will be very happy about any kinds of contributions from your end.

With kind regards,
Andreas.

[1] https://github.com/gafam/www.gafam.info/blob/main/doc/backlog.rst
[2] https://github.com/posterkit/posterkit-sandbox/blob/main/doc/backlog.rst
[3] https://github.com/posterkit/posterkit-sandbox/blob/main/posters/lqdn-gafam-campaign/backlog.rst

**Comment by amotl** [comment]
Hi again,

with dcdbd5d9b, some of the backlog items have been converted into corresponding issues, see #2, #3 and #4. Maybe you would like to work on any of those? As we see you are maintaining the [no-google] and [no-amazon] repositories, we believe #3 might resonate most with you?

Thank you in advance already!

With kind regards,
Andreas.

[no-google]: https://github.com/nickspaargaren/no-google
[no-amazon]: https://github.com/nickspaargaren/no-amazon

**Comment by nickspaargaren** [comment]
Closing this issue, the new issues are created, thanks!
